### ISSUE TITLE
curl: (52) Empty reply from server 

### ISSUE THREAD

**Issue by caclab** [jacopofar/neuraltalk2-web#5] opened 2017-04-13 10:03 UTC
Hi jacopofar, I'm trying to use your interface by using the addURL route. I am using a localhost nodejs server which hosts some images. When I pass the url object it gives me back the error curl: (52) Empty reply from server.

The curl command looks something like: 

curl -X POST -H "Content-Type: application/json" -d '{"url":"http://localhost:3000/1.jpg"}' 'http://localhost:5000/addURL'

I would appreciate if you have any suggestions.

Thanks in advance.

**Comment by jacopofar** [comment] 2017-04-13 10:40
I think the problem is how addresses are resolved inside Docker containers. The process inside the container sees its own separate interfaces, so for the application "localhost" is the Docker container loopback interface and not the system one where your server can be reached.

You can just pass it the LAN address (e.g. 192.168.1.3) instead of localhost, to remove the ambiguity.
You can test that the address can be reached by running `docker exec -it neuraltalk2-web bash` and running curl from there.

I should make the error message more clear, though

**Closed as completed by jacopofar** 2017-04-13 10:40 UTC

**Comment by caclab** [comment] 2017-04-14 03:16
Ok cool. I tried and it works from within the neuraltalk2-web bash and using the IP address instead of localhost.

Thanks!
